Feature/#253 선물하기 결제 완료 화면 구현 및 카카오톡 선물하기 API 연결
Nexters/Boolti-iOS pull request #273
Opened 2024-07-12 02:39 UTC by longlivedrgn

## 작업한 내용
- 선물하기 결제 완료 화면 구현 및 카카오톡 선물하기 API를 연결했어요.
- 지금 선물하기 flow 중간부터 구현을 해서 코드가 조금 복잡하긴한데, 궁금한 부분 있으면 알려주세요!

### 구현 사항
- 선물하기 완료 VC랑 일반 결제 완료 VC랑 너무 비슷해서, 사실 하나의 VC로 구현을 할까 고민을 했는데.. 그러면 너무 VC가 비대해질 거 같아서 그냥 새로운 `GiftCompletionViewController`를 정의하고, 일반 결제 완료 VC와 겹치는 부분을 protocol인 `CompletionViewControllerProtocol`로  빼서 구현했어요.
- 그 외에 DTO나 Entity도 선물하기 완료 VC와 일반 결제 완료 VC와 겹치는 부분은 protocol로 나눠서 정의했어요.
- 선물하기 결제 정보 API를 아직 쏠 수가 없어서(이전 Scene(결제)에서 giftID를 받을 수가 없어서) sample Data로 아래와 같이 넣어줬어요.
```swift
// in GiftCompletionViewModel 
    private func fetchGiftReservationDetail() -> Observable<GiftReservationDetailEntity> {
//        return self.ticketReservationsRepository.giftReservationDetail(with: "\(self.reservationId)")
        return Observable.just(GiftReservationDetailEntity(reservationID: 631, concertPosterImageURLPath: "https://yobwhuwlrftg22440152.gcdn.ntruss.com/show-images/2a94f9f9-ad56-426e-8ff9-aa9f2acafe81", concertTitle: "핫한 공연 예매의 시작, 불티", salesTicketName: "불티 일반 티켓", ticketType: Boolti.TicketType.sale, ticketCount: 1, depositDeadLine: "2024-08-02T23:59:59", paymentMethod: Optional(Boolti.PaymentMethod.simplePayment), totalPaymentAmount: "8,000", reservationStatus: Boolti.ReservationStatus.reservationCompleted, ticketingDate:  Optional("2024-07-11T15:24:01"), salesEndTime: "2024-08-02T23:59:59", csReservationID: "R-64-631", easyPayProvider: Optional("토스페이"), accountTransferBank: nil, paymentCardDetail: nil, showDate: Date(timeIntervalSince1970: 1720305600), giftID: 123, giftMessage: "호호", giftImageURLPath: "https://yobwhuwlrftg22440152.gcdn.ntruss.com/show-images/2a94f9f9-ad56-426e-8ff9-aa9f2acafe81", recipientName: "김용재", recipientPhoneNumber: "0101-234-2342"))
    }
```
- 그리고, 선물하기가 아니라 일반 결제 -> 선물하기 결제 완료 페이지로 넘어가도록 구현을 했어요. 추후에 선물하기 결제 API를 연결하면 거기에 맞게 선물하기 완료 페이지로 이어주면 될 거 같아요.
- 선물하기 결제 완료 페이지에서 `결제 내역 보기`버튼은 구현은 했는데, 임의로 giftID로 넘어가도록 구현했어요.

`카카오톡 공유하기`
- 웹이랑 이야기를 해서 카카오톡 공유하기 탭할 시 이동할 웹 사이트 주소를 받아야될 거 같아서 link 주소는 임의로 넣어두었어요.
- 공유하기에 들어가는 내용 중, 보내는 분의 필드 값이 없어서 일단은 Default 값으로 공유하기 내용을 채워넣었어요.
- 공유하기의 피그마 시안과 다르게 To. ~ 라는 부분이 볼드처리가 안되더라고요.. 그래서 요건 쫌 더 찾아보고 다른 거 붙히면서 수정해볼게요!

## 스크린샷
<img src="https://github.com/user-attachments/assets/4a69434b-6195-4b90-82fb-df0ddc4cb3f5" width="250"/>
<img src="https://github.com/user-attachments/assets/aaf01064-0974-40d9-9131-c20d1f44c427" width="250"/>

## 관련 이슈
- Resolved: #253

2024-07-13 15:47 UTC, wngus4296 requested changes
용재 너무 고생했다.. 
메이저한 건 스크롤뷰에 넣는 거만 수정해주면 될 것 같고 나머지 코멘트는 확인만 해주면 될 것 같습니당 🫡
API는 나중에 내가 앞쪽에 선물하기 흐름 완료하고 시작하면 될 듯!!

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/Network/DTO/Reservation/Response/GiftReservationDetailResponseDTO.swift
> +        let ticketType = self.salesTicketType == "SALE" ? TicketType.sale : TicketType.invitation
선물하기는 invitation이 없어서 무조건 SALE로 오는 것 같긴한데 혹시나 해서 달아둔 건가?!?

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Completion/GiftCompletion/GiftCompletionViewController.swift
> +    private lazy var giftNoticeLabel: BooltiUILabel = {
요친구는 lazy로 안해줘도 될 것 같다!!

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Completion/GiftCompletion/GiftCompletionViewController.swift
요거 돌려보니까 14pro정도 화면 크기 까지는 괜찮은 거 같은데 이거 보다 작은 거(height 812 이하)에서는 공연 정보부터 잘릴 것 같더라구 그래서 전체 스크롤뷰에 넣어줘야 할 것 같아!!

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Completion/Protocol/CompletionViewControllerProtocol.swift
용재 여기 너무 깔끔하게 잘했다.. 나도 ticketing detail 쪽 참고해서 리팩해볼게 👍👍

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/TicketingDetail/TicketingDetailViewController.swift
> +    typealias GiftID = Int
이거 진짜 내가 6차 끝나고 한 곳에 몰아넣을게 약속..

2024-07-13 15:47 UTC, wngus4296 commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Completion/GiftCompletion/GiftCompletionViewController.swift
> +        label.setHeadIndent()
이거 확인해봤는데, 기존에 내가 설정해뒀던 indent가 살짝 다른 거 같더라구
내가 이전뷰랑 연결시키면서 같이 확인할게!!

* 디자인
<img width="400" alt="image" src="https://github.com/user-attachments/assets/08ea190a-e051-41c1-a9b6-56b4e536df7d">  

* 실제 뷰
<img width="400" alt="image" src="https://github.com/user-attachments/assets/c50cd6c6-776a-42b4-bab4-b38b33786c37">

2024-07-16 16:02 UTC, longlivedrgn commented on Boolti/Boolti/Sources/Network/DTO/Reservation/Response/GiftReservationDetailResponseDTO.swift
> +        let ticketType = self.salesTicketType == "SALE" ? TicketType.sale : TicketType.invitation
sale만 받을 수 있도록 수정했습니다!

2024-07-16 16:02 UTC, longlivedrgn commented on Boolti/Boolti/Sources/UILayer/Concert/Ticketing/Completion/GiftCompletion/GiftCompletionViewController.swift
> +    private lazy var giftNoticeLabel: BooltiUILabel = {
요거 하나의 VC에서 분기처리하려고 해서 구현했던 건데 못 바꿨다!.. lazy 제거완료!

2024-07-21 15:10 UTC, merged